### ISSUE TITLE
Generate the Sudoku board with random numbers

### ISSUE THREAD

**Issue by anirudhRowjee** [anirudhRowjee/py-sudoku#3]
1. Start filling the first cell of the board with a random number from 1-9
2. For every cell thereafter, generate a random number. Based on whether or not all `segments` are valid, let that number be in that cell. Keep Generating Numbers until there's a valid number for the cell.
3. Finally, Once this completes, you'll be able to see a fully generated sudoku board. Print this out.

**Comment by anirudhRowjee** [comment]
Sure

**Comment by ishreya09** [comment]
can I get assigned to this? I would not be able to resolve issue #4 without generating the board.

**Comment by SrirangaLN** [comment]
Hey can I work on this?

**Comment by thecoderash** [comment]
Yes you can @SrirangaLN  now

**Comment by pramod1712** [comment]
Can I work on this issue?

**Comment by rithvikjayaram** [comment]
Can I work on this?

**Comment by thecoderash** [comment]
@M-Usman-Tahir please make a issue of your own to add in updates.

**Comment by omkarjois** [comment]
can i work on this

**Comment by prishagoel** [comment]
Hi, can I work on this?
