### ISSUE TITLE
Pretty-Print the Sudoku Board

### ISSUE THREAD

**Issue by anirudhRowjee** [anirudhRowjee/py-sudoku#4]
use a library like `tabulate` to make the board look nice.

**Comment by thecoderash** [comment]
@ishreya09 yes now you can

**Comment by shr218** [comment]
Can I work on this?

**Comment by advaithas** [comment]
can i work on this

**Comment by AyushmaanKaushik** [comment]
You've been assigned

**Comment by prishagoel** [comment]
Hi, can I please work on this?

**Comment by AyushmaanKaushik** [comment]
You guys have been assigned the issue
